import type { Metadata } from "next";
import "./globals.css";
import { QueryProvider } from "@/providers/QueryProvider";
import { SessionProvider } from "@/providers/SessionProvider";
import { AppProvider } from "@/providers/AppProvider";
import { Toaster } from "react-hot-toast";
import {
  geistSans,
  geistMono,
  beVietnamPro,
  craftyGirls,
  monsieurLaDoulaise,
  preahvihear,
  sedgwickAveDisplay,
  zenKakuGothicNew,
} from "@/constants/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${beVietnamPro.variable} ${craftyGirls.variable} ${monsieurLaDoulaise.variable} ${preahvihear.variable} ${sedgwickAveDisplay.variable} ${zenKakuGothicNew.variable} antialiased`}
      >
       <SessionProvider>
          <QueryProvider>
            <AppProvider>
              <Toaster position="top-right" />
              <main className="flex-1">{children}</main>
            </AppProvider>
          </QueryProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
